
# === POSTGRES CONFIG (Render) ===
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === CORS ===
# keep localhost temporarily for development ? remove later when frontend is live
app.cors.allowed-origins=https://dicestore.com,http://localhost:5173

# Show SQL queries
spring.jpa.show-sql=true

# Format SQL for readability
spring.jpa.properties.hibernate.format_sql=true

# Log SQL parameters (values in queries)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
